spring:
  application:
    name: service-zuul

server:
  address: localhost
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#以/api-a/开头的请求都转发给service-ribbon服务,以/api-b/开头的请求都转发给service-feign服务(名称自定义)
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
    #设置zuul超时时间:
    #host:
    #  socket-timeout-millis: 60000
    #  connect-timeout-millis: 60000