spring:
  application:
    name: service-ribbon

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#ribbon超时时间
#ribbon:
  #ReadTimeout: 60000
  #ConnectTimeout: 60000